clc;
clear;
close all;

Cmap1 = parula(4);

print_to_file = false;
% ------------------------------------------------------------------------
% insert terrestrial cratering rate curve from Ryder (2001), Marachi (2021), Nesvony
% (2022), Nekum and Ivanov (1994), for all craters (planetestimals, comets, asteroids)
% ------------------------------------------------------------------------

csv_read = readtable("Terrestrial_10km.csv");
data = table2array(csv_read);

% We will need to modify this factor as this will change the magnitude of 
% the terrestrial cratering rate (not impactors). 

% Recall that the total number of craters will equal the amount of
% planetestimal leftovers, asteroids, and comets that have hit Earth.

% The terrestrial cratering curve fitted here will reflect everything that
% has hit earth with D > 10 km.

% We know that the cratering rate from 500 MYA to now is mostly due to
% asteroid impacts and some comets, not planetestimal leftovers.

% Since this is the case, the terrestrial cratering curve must be extremely
% close to the asteroid impact flux curve of D > 10 km, which is already
% constrained by Nesvony et al. (2022) by equation 1. 

% We shall match the black input curve to the red curve to obtain the
% planetestimal impactor curves. 

scaling_factor = 0.00044;

x = data(:,1);
y = data(:,2);
earth_SA = 5.101e8;

% Fit the csv data to coefficients
%f1 = fit(x,y,'poly1');

% ------------------------------------------------------------------------
% Plot the fitted curves from 0 - 4.5GYA in increments of 1MYA
% ------------------------------------------------------------------------

t = linspace(0,4.5,4500);
F_total_fit_1 = scaling_factor * (t * 1.8e-05) * earth_SA;
F_total_fit_2 = scaling_factor * (1.466e-13 * exp(5.745*t)) * earth_SA;

F_total = F_total_fit_1 + F_total_fit_2;

% obtain the count of craters on earth > 10km per every million years
[count_crater_per_mya, total_craters, percent_craters_10km_per_mya] = count_per_mya(F_total); 

% ------------------------------------------------------------------------

% ------------------------------------------------------------------------
% Compute the impact flux of asteroids that are going to hit Earth.
% Equation generated by Nesvorny et al. (2022)
% This is the impact flux of asteroids > 10 km
% ------------------------------------------------------------------------

F_ast_1_10km = 225;
F_ast_2_10km = 3E-3;

F_ast_1 = F_ast_1_10km * exp(-(t*1000.0/65.0).^0.6);
F_ast_2 = F_ast_2_10km * (4570.0 - (t*1000.0));
F_ast = F_ast_1_10km * exp(-(t*1000.0/65.0).^0.6) + F_ast_2_10km * (4570.0 - (t*1000.0));

% Flip the array to produce similar curves, may need to flip equation above 
F_ast = flip(F_ast);

% obtain the count of asteroids hitting earth with D > 10km per every million years
[count_asteroids_10km_per_mya, total_asteroids, percent_asteroids_10km_per_mya] = count_per_mya(F_ast);

fig = figure(1);
subplot(1,2,1);
semilogy(t(2001:4490), F_ast(2001:4490), 'Color', Cmap1(1,:), 'LineWidth', 6, 'LineStyle','--')
set(gca,'XDir','reverse')

hold on
% ------------------------------------------------------------------------

% ------------------------------------------------------------------------
% Compute the impact flux of comets that are going to hit Earth.
% Equation generated by Nesvorny et al. (2022).
% However, the variables are inconsistent with the output data.
% We took figure 4.5, digitized the comet curve, and found a general function
% here valid for 4.5 - 2 GYA
% This is the impact flux of comets > 10 km
% ------------------------------------------------------------------------
a = 0.0001466;
b = 2.655;
c = 2.576e-18;
d = 10.16; 
F_com = a*exp(b*t) + c*exp(d*t) + t * 0.7183;

% obtain the count of comets hitting earth with D > 10km per every million years
[count_comets_10km_per_mya, total_comets, percent_comets_10km_per_mya] = count_per_mya(F_com);

semilogy(t(2001:4490), F_com(2001:4490), 'Color', Cmap1(2,:), 'LineWidth', 6, LineStyle=':')
hold on

% ------------------------------------------------------------------------
% Compute the total impact flux of comets and asteroids
% ------------------------------------------------------------------------
F_ast_com = F_ast + F_com;
semilogy(t(2001:4490), F_ast_com(2001:4490), 'Color', Cmap1(3,:), 'LineWidth', 6)
hold on
% ------------------------------------------------------------------------

% ------------------------------------------------------------------------
% Compute the impacting rate for the planetestimal leftovers
% ------------------------------------------------------------------------
%F_leftover = F_total - (F_ast + F_com);

% obtain the count of planetestimal leftovers hitting earth with D > 10km per every million years
%[count_leftovers_10km_per_mya, total_leftovers, percent_leftovers_10km_per_mya] = count_per_mya(F_leftover);
%semilogy(t, F_leftover, 'Color', 'green', 'LineWidth', 3)
%semilogy(t, F_leftover, 'Color', Cmap1(4,:), 'LineWidth', 6, LineStyle='-.')

% ------------------------------------------------------------------------

% ------------------------------------------------------------------------
% Apply plot modifiers to the first plot
% ------------------------------------------------------------------------
%title('Avg Total Melt Mass per MYA')

xlabel('Age (GYA)')
ylabel("Cumulative Impactor Count (d \geq 10 km)")
legend("Asteroids", "Comets","Asteroids & Comets",  Location="northeast", fontsize =18)
xlim([2,4]);
%ylim([1,10^3])
ax=gca;
ax.XAxis.FontSize = 18;
ax.YAxis.FontSize = 18;
ax.XLabel.FontSize = 18;
ax.YLabel.FontSize = 18;
ax.Title.FontSize = 18;
ax.LineWidth = 2;
ax.Legend.FontSize = 16;

fig.Units = 'centimeters';
fig.Position(3) = 25;
fig.Position(4) = 20;
saveas(ax,"d_10km_flux.png")




% ------------------------------------------------------------------------
% ------------------------------------------------------------------------
% scale the figure for D > 1km

% If following Nesvony et al (2022), then we get ~ 3x10^4 for asteroids at D > 1km
% rate_of_asteroid_impact_per_mya = 0.4; % current rate of asteroids/mya

% We can use the current rate of asteroids per mya at 0.4. Other sources
% claim that rate of asteroid impact per mya is 1.66666 or 1.5 (Wikipedia)

rate_of_asteroid_impact_per_mya = 1.66667; % current rate of asteroids/mya

scaling_factor_1km = rate_of_asteroid_impact_per_mya /F_ast_2_10km;
F_total_1km = F_ast_com * scaling_factor_1km;
F_ast_1km = F_ast * scaling_factor_1km;
F_com_1km = F_com * scaling_factor_1km;
%F_leftover_1km = F_leftover * scaling_factor_1km;

% make sure count is between 1.66 asteroids / mya or 
[count_asteroids_1km_per_mya, total_asteroids_1km, percent_asteroids_1km_per_mya] = count_per_mya(F_ast_1km);
[count_comets_1km_per_mya, total_comets_1km, percent_comets_1km_per_mya] = count_per_mya(F_com_1km);
%[count_leftovers_1km_per_mya, total_leftovers_1km, percent_leftovers_1km_per_mya] = count_per_mya(F_leftover_1km);



%fig = figure(2);

% semilogy(t(2001:4500), F_total_1km(2001:4500), 'Color', Cmap1(1,:), 'LineWidth', 6);
% hold on
subplot(1,2,2);
semilogy(t(2001:4500), F_ast_1km(2001:4500), 'Color', Cmap1(1,:), 'LineWidth', 6, 'LineStyle','--')
hold on
semilogy(t(2001:4500), F_com_1km(2001:4500), 'Color', Cmap1(2,:), 'LineWidth', 6, 'LineStyle',':')
hold on
semilogy(t, F_total_1km, 'Color', Cmap1(3,:), 'LineWidth', 6)
hold on
xlim([2,4])
% semilogy(t, F_leftover_1km, 'Color', Cmap1(4,:), 'LineWidth', 6, LineStyle='-.')
% hold on
set(gca,'XDir','reverse')

%grid on

%title('Avg Total Melt Mass per MYA')
xlabel('Age (GYA)')
ylabel("Cumulative Impactor Count (d \geq 1 km)")
legend("Asteroids", "Comets","Asteroids & Comets",  Location="northeast")
xlim([2.0,4.0]);
%ylim([1E3 1E5]);
ax=gca;
ax.XAxis.FontSize = 18;
ax.YAxis.FontSize = 18;
ax.XLabel.FontSize = 18;
ax.YLabel.FontSize = 18;
ax.Title.FontSize = 18;
ax.LineWidth = 2;
ax.Legend.FontSize = 16;

fig.Units = 'centimeters';
fig.Position(3) = 25;
fig.Position(4) = 20;


if print_to_file == true
    writematrix(count_asteroids_1km_per_mya(2000:4499), "../impactor_set_time_and_diameter/data_files/asteroid_01km_count_per_mya_20_45.csv")
    writematrix(count_comets_1km_per_mya(2000:4499), "../impactor_set_time_and_diameter/data_files/comet_01km_count_per_mya_20_45.csv")
    writematrix(count_leftovers_1km_per_mya(2000:4499), "../impactor_set_time_and_diameter/data_files/leftover_01km_count_per_mya_20_45.csv")
    
    writematrix(count_asteroids_10km_per_mya(2000:4499), "../impactor_set_time_and_diameter/data_files/asteroid_10km_count_per_mya_20_45.csv")
    writematrix(count_comets_10km_per_mya(2000:4499), "../impactor_set_time_and_diameter/data_files/comet_10km_count_per_mya_20_45.csv")
    writematrix(count_leftovers_10km_per_mya(2000:4499), "../impactor_set_time_and_diameter/data_files/leftover_10km_count_per_mya_20_45.csv")

end

saveas(ax,"d_1km_flux.png")






